_BASE_: "Base-CalibNet.yaml"
MODEL:
  WEIGHTS: ""  # download the pretrained weights
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  CALIBNET:
    DECODER:
      NUM_KERNELS: 50
TEST:
  DETECTIONS_PER_IMAGE: 50
