_BASE_: "Base-CalibNet.yaml"
MODEL:
  WEIGHTS: "" # download the pretrained weights
  BACKBONE:
    NAME: "build_p2t_backbone"
  CALIBNET:
    DECODER:
      NUM_KERNELS: 50
TEST:
  DETECTIONS_PER_IMAGE: 50
